### ISSUE TITLE
Unity 4.0.1 and HangFire 1.5.3 build issues

### ISSUE THREAD

**Issue by RupertAvery** [phenixdotnet/Hangfire.Unity#2]
I recently updated a project to use Unity 4.0.1 and the HangFire.Core 1.5.3 and it seems that it doesn't compile anymore, as the UnityJobActivator is looking for Unity 3.5.0.0

I was able to fix it by recompiling against the latest dependencies, but I would appreciate it very much if you could put up an official build (1.0.1?) with the latest versions.

Thanks!

**Comment by phenixdotnet** [comment]
Hi.

The source and NuGet package has been updated.

Regards
Vincent

**Comment by RupertAvery** [comment]
That was fast! Thanks!
