### ISSUE TITLE
Unity 5.x

### ISSUE THREAD

**Issue by michaeltheyeti** [phenixdotnet/Hangfire.Unity#7]
The namespace for Unity is from Unity 4.x I believe (Microsoft.Practices.Unity).

Could this be updated to use the new 5.x namespace (Unity)?

Thanks

**Comment by phenixdotnet** [comment]
Hi,

Issue resolved by https://github.com/phenixdotnet/Hangfire.Unity/pull/9.
Package Hangfire.Unity 1.4.0 is now available in NuGet.
